apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    app: kubernetes-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      type: mongo
  template:
    metadata:
      labels:
        type: mongo
    spec: 
        containers:
          - name: mongo
            image: mongo
            ports: 
              - containerPort: 27017


