apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: kubernetes-learning
    type: database-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 27017
      name: mongo
      port: 27017
      protocol: TCP
  selector:
     type: mongo
