apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: kubernetes-learning
    type: loadbalancer-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 3000
      port: 1156
  selector:
     type: front-end
