apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-application-deploy
  labels:
    app: kubernetes-learning
spec:
  replicas: 3
  selector:
    matchLabels:
      type: back-end
  template:
    metadata:
      labels:
        type: back-end
    spec: 
        containers:
          - name: node-backend
            image: rahulpandey1589/nodeapi:1.1.6
            ports: 
              - containerPort: 1158
            env:
              - name: MONGO_URI
                value: 'mongodb://mongodbexplore:27017/health_logger?retryWrites=true&w=majority'
              