apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: kubernetes-learning
    type: loadbalancer-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 1158
      port: 1189
  selector:
     type: back-end
